# Copyright (c) 2020-2021 Advanced Robotics at the University of Washington <robomstr@uw.edu>
#
# This file is part of Taproot.
#
# Taproot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Taproot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Taproot.  If not, see <https://www.gnu.org/licenses/>.

default:
  image: aruw/mcb-2020-gitlab-ci:2021-06-02.1

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  NUM_JOBS: 4
  ADDITIONAL_CI_BUILD_ARGS: -j${NUM_JOBS} additional-ccflags=-Werror

.default_only: &default_only
  - merge_requests
  - master
  - develop
  - schedules

.verification_only: &verification_only
  - merge_requests
  - master
  - develop

.verification_except: &verification_except
  - schedules 

stages:
  - Initial Verification
  - Generate Test Project
  - Build all Targets
  - Deploy Pages

before_script:
  - python3 -V # Print out python version for debugging

# Initial verification

"Clang Format":
  stage: Initial Verification
  needs: []
  script:
    - "true"
    # - python3 /run-clang-format.py --clang-format-executable clang-format-10 -r src/ test/
  only: *verification_only
  except: *verification_except

"Policy Checks":
  stage: Initial Verification
  needs: []
  script:
    - python3 ./scripts/check_singleton_drivers.py src
    - python3 ./scripts/check_license_headers.py
  variables:
    GIT_SUBMODULE_STRATEGY: none
  only: *verification_only
  except: *verification_except

.run_lbuild:
  script:
    - cd test-project && lbuild build && cd ..
  cache:
    untracked: true
    key: ${BOARD_TYPE}_project
    paths:
      - test-project

.type_a_config_cache:
  needs: ["Type A: Generate Test Project"]
  dependencies: ["Type A: Generate Test Project"]
  cache:
    key: type_a_project
    untracked: true

.type_c_config_cache:
  needs: ["Type C: Generate Test Project"]
  dependencies: ["Type C: Generate Test Project"]
  cache:
    key: type_c_project
    untracked: true

.mcb_build:
  stage: "Build all Targets"
  only: *default_only
  script:
    - cd test-project
    - scons build $ADDITIONAL_CI_BUILD_ARGS

.sim_build:
  stage: "Build all Targets"
  only: *default_only
  script:
    - cd test-project
    - scons build-sim profile=fast $ADDITIONAL_CI_BUILD_ARGS

.tests_build:
  stage: "Build all Targets"
  only: *default_only
  script:
    - cd test-project
    - scons run-tests-gcov profile=fast $ADDITIONAL_CI_BUILD_ARGS
    - valgrind --leak-check=full --error-exitcode=1 --show-leak-kinds=all build/tests/scons-fast/mcb-project-tests.elf
    - cd .. && gcovr -g --xml > cobertura.xml
    - 'sed -i "s;filename=\"taproot/;filename=\";g" cobertura.xml'
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-tests"
    reports:
      cobertura: cobertura.xml
    expire_in: 2 weeks

"Type A: Generate Test Project":
  needs: []
  only: *default_only
  stage: Generate Test Project
  extends:
    - .run_lbuild
  variables:
    BOARD_TYPE: type_a

"Type C: Generate Test Project":
  needs: []
  stage: Generate Test Project
  only: *default_only
  extends:
    - .run_lbuild
  before_script:
    - cd test-project
    - sed -i '/<!-- For RoboMaster Development Board Type A -->/,/<!-- End For RoboMaster Development Board Type A -->/c\' project.xml
    - sed -i '/<!-- For RoboMaster Development Board Type C --> <!--/c\' project.xml
    - sed -i '/--> <!-- End For RoboMaster Development Board Type C -->/c\' project.xml
    - cd ..
  variables:
    BOARD_TYPE: type_c

# Type A CI
"Type A: MCB Build":
  extends:
    - .type_a_config_cache
    - .mcb_build

"Type A: Sim Build":
  extends:
    - .type_a_config_cache
    - .sim_build

"Type A: Tests Build":
  extends:
    - .type_a_config_cache
    - .tests_build

# Type C CI
"Type C: MCB Build":
  extends:
    - .type_c_config_cache
    - .mcb_build

"Type C: Sim Build":
  extends:
    - .type_c_config_cache
    - .sim_build

"Type C: Tests Build":
  extends:
    - .type_c_config_cache
    - .tests_build

# Pages deploy

"Generate Docs":
  image: alpine
  needs: []
  stage: Deploy Pages
  before_script:
    - apk update
    - apk add py-pip python3-dev
    - apk add make
    - apk add --no-cache g++ gcc libxml2-dev libxslt-dev
    - pip3 install lxml
    - pip3 install sphinx breathe exhale
    - pip install sphinx_rtd_theme
    - apk add doxygen
  script:
    - cd docs && make html
    - mv _build/html/ ../public/
  artifacts:
    paths:
      - public
  only:
    - develop
    - merge_requests
  environment:
    name: "docs preview"
    url: "https://aruw.gitlab.io/-/controls/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/public/index.html"

pages:
  image: alpine
  needs: ["Generate Docs"]
  dependencies: ["Generate Docs"]
  stage: Deploy Pages
  before_script:
    - "true"
  script: "true"
  artifacts:
    paths:
      - public
  only:
    - develop
  except:
    - schedules
